NAMED_COLORS = ['green', 'red', 'orange', 'blue', 'yellow', 'magenta', 'white', 'cyan']
PERSON_CLASS_ID_COCO = 1
PERSON_CLASS_ID_RETINANET = 0

PERFECT_PERSON_RATIO = 3.8
MIN_PERSON_RATIO = 2
MAX_PERSON_RATIO = 5

MIN_PERSON_HEIGHT = 100
# MIN_PERSON_WIDTH = 50
MIN_PERSON_WIDTH = MIN_PERSON_HEIGHT / PERFECT_PERSON_RATIO


PERFECT_PERSON_HEIGHT = 110
# PERFECT_PERSON_WIDTH = 55
PERFECT_PERSON_WIDTH = PERFECT_PERSON_HEIGHT / PERFECT_PERSON_RATIO

MAX_PERSON_HEIGHT = 120
# MAX_PERSON_WIDTH = 60
MAX_PERSON_WIDTH = MAX_PERSON_HEIGHT / PERFECT_PERSON_RATIO
